[build]
  command = "npm run netlify:build"
  publish = ".next"

[build.environment]
  PRISMA_CLI_BINARY_TARGETS = "darwin,darwin-arm64,debian-openssl-1.1.x"

[[plugins]]
  package = "@netlify/plugin-nextjs"
