[build]
  command = "prisma generate && prisma migrate deploy && (prisma db seed || echo 'Seed failed but continuing build') && next build"
  publish = ".next"

[build.environment]
  PRISMA_CLI_BINARY_TARGETS = "native,rhel-openssl-3.0.x,debian-openssl-1.1.x"

[[plugins]]
  package = "@netlify/plugin-nextjs"
